spring:
  profiles:
    active: local # 기본 환경 선택
  jwt:
    secret: dabinKey
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  login:
    kakaoAuthUrl: https://kauth.kakao.com
    kakaoApiKey: e960a5e5eef1a420a189423849ac8960
    redirectURI: http://localhost:8080/login/oauth_kakao
    getUserInfoUrl: https://kapi.kakao.com/v2/user/me
    kakaoLogoutUrl: https://kapi.kakao.com/v1/user/logout
# local 환경
# data: classpath:data-h2.sql
# 시작할때 실행시킬 script
---
spring:
  profiles: local
  datasource:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

cloud.aws:
  region.static: ap-northeast-2
  stack.auto: false
# 운영 환경
---
spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 8081

---
spring.profiles: set2
spring.profiles.include: real-db

server:
  port: 8082

